# Generated by Django 6.0.6 on 2026-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
